# Generated by Django 3.1 on 2020-08-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_title', models.CharField(max_length=200)),
                ('board_contents', models.TextField()),
                ('board_writer', models.CharField(max_length=200)),
                ('board_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
