# Generated by Django 3.1 on 2020-09-30 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lob', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basket',
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='board_id',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
