# Generated by Django 3.1 on 2020-09-30 14:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lob', '0004_auto_20200930_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket_contents', models.TextField()),
                ('basket_reservationTime', models.TimeField()),
                ('basket_info', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_id', models.AutoField(primary_key=True, serialize=False)),
                ('board_title', models.CharField(max_length=200)),
                ('board_contents', models.TextField()),
                ('board_writer', models.CharField(max_length=200)),
                ('board_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_date', models.DateTimeField()),
                ('food_name', models.CharField(max_length=100)),
                ('food_expirationDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('food_recodeDate', models.DateTimeField(auto_now_add=True)),
                ('food_expirationDate', models.DateTimeField(default=datetime.timezone)),
                ('food_info', models.IntegerField()),
                ('food_remainDate', models.DateTimeField(default=datetime.timezone)),
                ('food_img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=32)),
                ('user_profile', models.ImageField(upload_to='')),
                ('user_rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_contents', models.TextField()),
                ('comment_writer', models.CharField(max_length=200)),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lob.board')),
            ],
        ),
    ]
