# Generated by Django 3.1 on 2020-10-03 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lob', '0005_basket_board_calendar_comment_food_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
    ]
