# Generated by Django 3.1 on 2020-10-03 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lob', '0015_food'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
    ]
