# Generated by Django 3.1 on 2020-10-06 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lob', '0017_food'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basket',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
