# Generated by Django 3.1 on 2020-10-06 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lob', '0021_basket_food'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
    ]
